# Generated by Django 4.2.17 on 2025-01-12 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=2)),
                ('type', models.CharField(choices=[('SH', 'Shirt'), ('PA', 'Pants'), ('JA', 'Jacket'), ('TS', 'T-Shirt'), ('SK', 'Skirt'), ('DR', 'Dress'), ('OT', 'Other')], default='SH', max_length=2)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
